cfg:
  sample_rate: 16000
  log_prediction: true
  ctc_reduction: mean_batch
  train_ds:
    manifest_filepath: /home/paperspace/conformer/dataset_train/manifest.json
    sample_rate: 16000
    batch_size: 32
    shuffle: true
    num_workers: 16
    pin_memory: true
    use_start_end_token: false
    trim_silence: false
    max_duration: 45
    min_duration: 0.1
    shuffle_n: 2048
    is_tarred: false
    tarred_audio_filepaths: /data/train/audio__OP_0..1023_CL_.tar
  validation_ds:
    manifest_filepath: /home/paperspace/conformer/dataset_train/manifest.json
    sample_rate: 16000
    batch_size: 32
    shuffle: false
    num_workers: 16
    pin_memory: true
    use_start_end_token: false
  test_ds:
    manifest_filepath: /home/paperspace/conformer/dataset_train/manifest.json
    sample_rate: 16000
    batch_size: 32
    shuffle: false
    num_workers: 16
    pin_memory: true
    use_start_end_token: false
  tokenizer:
    dir: /tokenizers/tokenizer_spe_unigram_v128/
    type: bpe
    model_path: nemo:f6ecea98695443ff9bf46755beaea4f8_tokenizer.model
    vocab_path: nemo:4708865ea7a34bff858c161e21bff7da_vocab.txt
    spe_tokenizer_vocab: nemo:3f63e59c15164a59bf93036f4e3a6789_tokenizer.vocab
  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    sample_rate: 16000
    normalize: per_feature
    window_size: 0.025
    window_stride: 0.01
    window: hann
    features: 80
    n_fft: 512
    log: true
    frame_splicing: 1
    dither: 1.0e-05
    pad_to: 0
    pad_value: 0.0
  spec_augment:
    _target_: nemo.collections.asr.modules.SpectrogramAugmentation
    freq_masks: 2
    time_masks: 10
    freq_width: 27
    time_width: 0.05
  encoder:
    _target_: nemo.collections.asr.modules.ConformerEncoder
    feat_in: 80
    feat_out: -1
    n_layers: 18
    d_model: 512
    subsampling: striding
    subsampling_factor: 4
    subsampling_conv_channels: 512
    ff_expansion_factor: 4
    self_attention_model: rel_pos
    n_heads: 8
    att_context_size:
    - -1
    - -1
    xscaling: true
    untie_biases: true
    pos_emb_max_len: 5000
    conv_kernel_size: 31
    dropout: 0.1
    dropout_emb: 0.0
    dropout_att: 0.1
  decoder:
    _target_: nemo.collections.asr.modules.ConvASRDecoder
    feat_in: 512
    num_classes: 128
    vocabulary:
    - <unk>
    - ▁
    - e
    - t
    - s
    - 'n'
    - i
    - en
    - m
    - er
    - a
    - u
    - r
    - h
    - o
    - l
    - d
    - b
    - f
    - g
    - te
    - ch
    - ▁w
    - k
    - z
    - ▁die
    - ▁und
    - st
    - ä
    - ▁der
    - ▁k
    - w
    - p
    - ü
    - ▁ge
    - ge
    - ▁zu
    - ▁be
    - in
    - ▁f
    - ▁g
    - sch
    - ▁das
    - le
    - ▁in
    - an
    - de
    - ▁ein
    - gen
    - ung
    - el
    - ▁er
    - ö
    - ▁b
    - ig
    - ra
    - ▁ha
    - cht
    - lich
    - re
    - ▁ver
    - ▁sch
    - al
    - ten
    - ▁sie
    - ll
    - ar
    - ▁den
    - ▁da
    - or
    - ▁so
    - it
    - li
    - v
    - ri
    - au
    - hr
    - ß
    - ▁ich
    - den
    - la
    - ▁nicht
    - ▁an
    - ▁p
    - ▁un
    - ck
    - ben
    - ▁mit
    - and
    - ▁auf
    - ▁eine
    - ▁st
    - ▁sich
    - ▁es
    - ▁wir
    - ▁ma
    - ein
    - ▁ist
    - tz
    - ▁sein
    - ro
    - ▁war
    - ▁von
    - rei
    - ▁se
    - ▁wie
    - ▁dem
    - j
    - ▁ihr
    - ▁als
    - ▁aus
    - ▁des
    - ▁diese
    - ▁im
    - ▁vor
    - ▁auch
    - ische
    - ▁sa
    - und
    - ▁nach
    - ▁her
    - ▁alle
    - ▁für
    - ▁wei
    - c
    - 'y'
    - x
    - q
  optim:
    name: adamw
    lr: 2.0
    betas:
    - 0.9
    - 0.98
    weight_decay: 0.001
    sched:
      name: NoamAnnealing
      d_model: 512
      warmup_steps: 10000
      warmup_ratio: null
      min_lr: 1.0e-06
  target: nemo.collections.asr.models.ctc_bpe_models.EncDecCTCModelBPE
  nemo_version: 1.18.0
  decoding:
    strategy: greedy
    preserve_alignments: null
    compute_timestamps: null
    word_seperator: ' '
    ctc_timestamp_type: all
    batch_dim_index: 0
    greedy:
      preserve_alignments: false
      compute_timestamps: false
      preserve_frame_confidence: false
      confidence_method_cfg: null
    beam:
      beam_size: 4
      search_type: default
      preserve_alignments: false
      compute_timestamps: false
      return_best_hypothesis: true
      beam_alpha: 1.0
      beam_beta: 0.0
      kenlm_path: null
      flashlight_cfg:
        lexicon_path: null
        boost_path: null
        beam_size_token: 16
        beam_threshold: 20.0
        unk_weight: -.inf
        sil_weight: 0.0
      pyctcdecode_cfg:
        beam_prune_logp: -10.0
        token_min_logp: -5.0
        prune_history: false
        hotwords: null
        hotword_weight: 10.0
    confidence_cfg:
      preserve_frame_confidence: false
      preserve_token_confidence: false
      preserve_word_confidence: false
      exclude_blank: true
      aggregation: min
      method_cfg:
        name: entropy
        entropy_type: tsallis
        temperature: 0.33
        entropy_norm: exp
